HexagonRoot:
    center_label: center_label 
    corner_label: corner_label 
    edge_label: edge_label 
    Label:
        id: center_label
        text: "center"
        pos_hint: {}
        size_hint: None, None
    Label:
        id: corner_label
        text: "corner"
        size_hint: None, None
        pos_hint: {}
    Label:
        id: edge_label
        text: "edge"
        size_hint: None, None
        pos_hint: {}
